### ISSUE TITLE
Error after each command

### ISSUE THREAD

**Issue by aussieW** [forslund/white-house-adventure#2]
Hi
Just been playing with this skill a bit and noticed that after each command is sent it executes the command and then throws an error in the converse method. I've not had any experience with the converse method, but it doesn't seem like proper behavior.

```
08:28:04.798 - SKILLS - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-us", "utterances": ["play zork"]}, "context": null}
08:28:04.823 - SKILLS - DEBUG - {"type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": -334948055, "utterances": ["play zork"]}, "context": null}
[u'play zork']
08:28:04.883 - SKILLS - DEBUG - {"type": "skill.converse.response", "data": {"skill_id": -334948055, "result": false}, "context": null}
08:28:04.964 - SKILLS - DEBUG - {"type": "-334948055:PlayZork", "data": {"confidence": 1.0, "target": null, "Zork": "zork", "intent_type": "-334948055:PlayZork", "Play": "play", "__tags__": [{"end_token": 0, "start_token": 0, "from_context": false, "entities": [{"confidence": 1.0, "data": [["play", "AudioRecordSkillPlayVerb"], ["Play", "Concept"], ["play", "Play"]], "key": "play", "match": "play"}], "key": "play", "match": "play"}, {"end_token": 1, "start_token": 1, "from_context": false, "entities": [{"confidence": 1.0, "data": [["zork", "Zork"], ["Zork", "Concept"]], "key": "zork", "match": "zork"}], "key": "zork", "match": "zork"}], "utterance": "play zork"}, "context": {"target": null}}
08:28:05.008 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "play_zork"}, "context": null}
08:28:05.036 - SKILLS - DEBUG - {"type": "speak", "data": {"expect_response": true, "utterance": "\nWest of House\nYou are standing in an open field west of a white house, with a boarded\nfront door.\nThere is a small mailbox here.\n\n"}, "context": null}
08:28:05.065 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "play_zork"}, "context": null}
08:28:05.128 - SKILLS - DEBUG - {"type": "enclosure.eyes.blink", "data": {"side": "b"}, "context": null}
08:28:05.162 - SKILLS - DEBUG - {"type": "recognizer_loop:audio_output_start", "data": {}, "context": null}
08:28:05.172 - skill-mopidy-local - INFO - Mopidy: Lowering volume.
08:28:05.198 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:28:05.242 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:28:15.294 - SKILLS - DEBUG - {"type": "recognizer_loop:audio_output_end", "data": {}, "context": null}
08:28:15.300 - skill-mopidy-local - INFO - Mopidy: Restoring volume.
08:28:15.336 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:28:15.373 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:28:15.456 - SKILLS - DEBUG - {"type": "recognizer_loop:record_begin", "data": {}, "context": null}
08:28:15.469 - skill-mopidy-local - INFO - Mopidy: Lowering volume.
08:28:15.503 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:28:15.545 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:28:18.304 - SKILLS - DEBUG - {"type": "recognizer_loop:record_end", "data": {}, "context": null}
08:28:18.313 - skill-mopidy-local - INFO - Mopidy: Restoring volume.
08:28:18.334 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:28:18.384 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:28:18.436 - SKILLS - DEBUG - {"type": "recognizer_loop:wakeword", "data": {"session": "ffd346a5-740b-4a59-9081-924d4c02485d", "utterance": "hey victoria"}, "context": null}
08:28:26.528 - SKILLS - DEBUG - {"type": "mycroft.speech.recognition.unknown", "data": {}, "context": null}
08:28:26.563 - SKILLS - DEBUG - {"type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": -334948055, "utterances": null}, "context": null}
None
08:28:26.572 - mycroft.skills.main:handle_converse_request:392 - ERROR - Error in converse method for skill -334948055
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.12-py2.7.egg/mycroft/skills/main.py", line 386, in handle_converse_request
    result = instance.converse(utterances, lang)
  File "/opt/mycroft/skills/white-house-adventure/__init__.py", line 81, in converse
    utterance = utterance[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
08:28:26.615 - SKILLS - DEBUG - {"type": "skill.converse.response", "data": {"skill_id": 0, "result": false}, "context": null}
08:28:31.281 - mycroft.skills.settings:_request_my_settings:418 - INFO - getting skill settings from server for WeatherSkill
08:28:31.297 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
08:28:32.516 - mycroft.skills.settings:_request_my_settings:418 - INFO - getting skill settings from server for StreamingRadioSkill
08:28:32.533 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
08:28:33.207 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/c4c055f3-1610-4ac0-9f82-f14209b9208e/skill HTTP/1.1" 200 4394
08:28:33.243 - mycroft.skills.settings:_upload_meta:277 - INFO - sending settingsmeta.json for WeatherSkill to servers
08:28:33.257 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
08:28:34.389 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/c4c055f3-1610-4ac0-9f82-f14209b9208e/skill HTTP/1.1" 200 4394
08:28:47.519 - SKILLS - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-us", "utterances": ["open mailbox"]}, "context": null}
08:28:47.561 - SKILLS - DEBUG - {"type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": -334948055, "utterances": ["open mailbox"]}, "context": null}
[u'open mailbox']
08:28:47.610 - SKILLS - DEBUG - {"type": "speak", "data": {"expect_response": true, "utterance": "\nOpening the small mailbox reveals a leaflet.\n\n"}, "context": null}
08:28:47.644 - SKILLS - DEBUG - {"type": "skill.converse.response", "data": {"skill_id": -334948055, "result": true}, "context": null}
08:28:47.681 - SKILLS - DEBUG - {"type": "enclosure.eyes.blink", "data": {"side": "b"}, "context": null}
08:28:47.710 - SKILLS - DEBUG - {"type": "recognizer_loop:audio_output_start", "data": {}, "context": null}
08:28:47.719 - skill-mopidy-local - INFO - Mopidy: Lowering volume.
08:28:47.751 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:28:47.787 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:28:49.472 - mycroft.skills.settings:_send_settings_meta:194 - ERROR - HTTPSConnectionPool(host='api.mycroft.ai', port=443): Read timed out. (read timeout=15)
08:28:49.489 - mycroft.skills.settings:_save_hash:320 - INFO - saving hash skill-weather-4b13c25674093089cb0422992628aa92
08:28:51.445 - SKILLS - DEBUG - {"type": "recognizer_loop:audio_output_end", "data": {}, "context": null}
08:28:51.456 - skill-mopidy-local - INFO - Mopidy: Restoring volume.
08:28:51.479 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:28:51.503 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:28:51.647 - SKILLS - DEBUG - {"type": "recognizer_loop:record_begin", "data": {}, "context": null}
08:28:51.663 - skill-mopidy-local - INFO - Mopidy: Lowering volume.
08:28:51.693 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:28:51.731 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:28:54.544 - SKILLS - DEBUG - {"type": "recognizer_loop:record_end", "data": {}, "context": null}
08:28:54.552 - skill-mopidy-local - INFO - Mopidy: Restoring volume.
08:28:54.571 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:28:54.608 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:28:54.635 - SKILLS - DEBUG - {"type": "recognizer_loop:wakeword", "data": {"session": "ffd346a5-740b-4a59-9081-924d4c02485d", "utterance": "hey victoria"}, "context": null}
08:29:00.893 - SKILLS - DEBUG - {"type": "mycroft.speech.recognition.unknown", "data": {}, "context": null}
08:29:00.921 - SKILLS - DEBUG - {"type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": -334948055, "utterances": null}, "context": null}
None
08:29:00.929 - mycroft.skills.main:handle_converse_request:392 - ERROR - Error in converse method for skill -334948055
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.12-py2.7.egg/mycroft/skills/main.py", line 386, in handle_converse_request
    result = instance.converse(utterances, lang)
  File "/opt/mycroft/skills/white-house-adventure/__init__.py", line 81, in converse
    utterance = utterance[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
08:29:00.954 - SKILLS - DEBUG - {"type": "skill.converse.response", "data": {"skill_id": 0, "result": false}, "context": null}
08:29:10.628 - SKILLS - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-us", "utterances": ["take leaflet"]}, "context": null}
08:29:10.663 - SKILLS - DEBUG - {"type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": -334948055, "utterances": ["take leaflet"]}, "context": null}
[u'take leaflet']
08:29:10.695 - SKILLS - DEBUG - {"type": "speak", "data": {"expect_response": true, "utterance": "\nTaken.\n\n"}, "context": null}
08:29:10.741 - SKILLS - DEBUG - {"type": "skill.converse.response", "data": {"skill_id": -334948055, "result": true}, "context": null}
08:29:10.810 - SKILLS - DEBUG - {"type": "enclosure.eyes.blink", "data": {"side": "b"}, "context": null}
08:29:10.847 - SKILLS - DEBUG - {"type": "recognizer_loop:audio_output_start", "data": {}, "context": null}
08:29:10.855 - skill-mopidy-local - INFO - Mopidy: Lowering volume.
08:29:10.908 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:29:10.945 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:29:11.757 - SKILLS - DEBUG - {"type": "recognizer_loop:audio_output_end", "data": {}, "context": null}
08:29:11.763 - skill-mopidy-local - INFO - Mopidy: Restoring volume.
08:29:11.789 - SKILLS - DEBUG - {"type": "enclosure.eyes.blink", "data": {"side": "b"}, "context": null}
08:29:11.824 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:29:11.843 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:29:11.985 - SKILLS - DEBUG - {"type": "recognizer_loop:record_begin", "data": {}, "context": null}
08:29:11.991 - skill-mopidy-local - INFO - Mopidy: Lowering volume.
08:29:12.025 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:29:12.067 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:29:14.771 - SKILLS - DEBUG - {"type": "recognizer_loop:record_end", "data": {}, "context": null}
08:29:14.786 - skill-mopidy-local - INFO - Mopidy: Restoring volume.
08:29:14.798 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:29:14.834 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:29:14.903 - SKILLS - DEBUG - {"type": "recognizer_loop:wakeword", "data": {"session": "ffd346a5-740b-4a59-9081-924d4c02485d", "utterance": "hey victoria"}, "context": null}
08:29:23.477 - SKILLS - DEBUG - {"type": "mycroft.speech.recognition.unknown", "data": {}, "context": null}
08:29:23.506 - SKILLS - DEBUG - {"type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": -334948055, "utterances": null}, "context": null}
None
08:29:23.516 - mycroft.skills.main:handle_converse_request:392 - ERROR - Error in converse method for skill -334948055
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.12-py2.7.egg/mycroft/skills/main.py", line 386, in handle_converse_request
    result = instance.converse(utterances, lang)
  File "/opt/mycroft/skills/white-house-adventure/__init__.py", line 81, in converse
    utterance = utterance[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
08:29:23.544 - SKILLS - DEBUG - {"type": "skill.converse.response", "data": {"skill_id": 0, "result": false}, "context": null}
08:29:28.562 - SKILLS - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-us", "utterances": ["read leaflet"]}, "context": null}
08:29:28.592 - SKILLS - DEBUG - {"type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": -334948055, "utterances": ["read leaflet"]}, "context": null}
[u'read leaflet']
08:29:28.664 - SKILLS - DEBUG - {"type": "speak", "data": {"expect_response": true, "utterance": "\n\"WELCOME TO ZORK!\n\nZORK is a game of adventure, danger, and low cunning. In it you will\nexplore some of the most amazing territory ever seen by mortals. No\ncomputer should be without one!\"\n\n"}, "context": null}
08:29:28.688 - SKILLS - DEBUG - {"type": "skill.converse.response", "data": {"skill_id": -334948055, "result": true}, "context": null}
08:29:28.763 - SKILLS - DEBUG - {"type": "enclosure.eyes.blink", "data": {"side": "b"}, "context": null}
08:29:28.791 - SKILLS - DEBUG - {"type": "recognizer_loop:audio_output_start", "data": {}, "context": null}
08:29:28.807 - skill-mopidy-local - INFO - Mopidy: Lowering volume.
08:29:28.826 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:29:28.874 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:29:34.434 - mycroft.skills.settings:_request_my_settings:418 - INFO - getting skill settings from server for StreamingRadioSkill
08:29:34.449 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
08:29:37.194 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/c4c055f3-1610-4ac0-9f82-f14209b9208e/skill HTTP/1.1" 200 4394
08:29:44.093 - SKILLS - DEBUG - {"type": "recognizer_loop:audio_output_end", "data": {}, "context": null}
08:29:44.103 - skill-mopidy-local - INFO - Mopidy: Restoring volume.
08:29:44.122 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:29:44.153 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:29:44.288 - SKILLS - DEBUG - {"type": "recognizer_loop:record_begin", "data": {}, "context": null}
08:29:44.306 - skill-mopidy-local - INFO - Mopidy: Lowering volume.
08:29:44.344 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:29:44.398 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.lower_volume"}, "context": null}
08:29:47.147 - SKILLS - DEBUG - {"type": "recognizer_loop:record_end", "data": {}, "context": null}
08:29:47.152 - skill-mopidy-local - INFO - Mopidy: Restoring volume.
08:29:47.184 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:29:47.224 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "Mopidy Local Skill.restore_volume"}, "context": null}
08:29:47.251 - SKILLS - DEBUG - {"type": "recognizer_loop:wakeword", "data": {"session": "ffd346a5-740b-4a59-9081-924d4c02485d", "utterance": "hey victoria"}, "context": null}
08:29:49.505 - mycroft.skills.settings:_request_my_settings:418 - INFO - getting skill settings from server for WeatherSkill
08:29:49.517 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
08:29:51.148 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/c4c055f3-1610-4ac0-9f82-f14209b9208e/skill HTTP/1.1" 200 4394
08:29:51.203 - mycroft.skills.settings:_upload_meta:277 - INFO - sending settingsmeta.json for WeatherSkill to servers
08:29:51.243 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
08:29:54.296 - SKILLS - DEBUG - {"type": "mycroft.speech.recognition.unknown", "data": {}, "context": null}
08:29:54.326 - SKILLS - DEBUG - {"type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": -334948055, "utterances": null}, "context": null}
None
08:29:54.335 - mycroft.skills.main:handle_converse_request:392 - ERROR - Error in converse method for skill -334948055
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.12-py2.7.egg/mycroft/skills/main.py", line 386, in handle_converse_request
    result = instance.converse(utterances, lang)
  File "/opt/mycroft/skills/white-house-adventure/__init__.py", line 81, in converse
    utterance = utterance[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
08:29:54.389 - SKILLS - DEBUG - {"type": "skill.converse.response", "data": {"skill_id": 0, "result": false}, "context": null}
08:30:07.517 - mycroft.skills.settings:_send_settings_meta:194 - ERROR - HTTPSConnectionPool(host='api.mycroft.ai', port=443): Read timed out. (read timeout=15)
```

**Comment by forslund** [comment]
Thanks for reporting. I noticed this myself yesterday, I'm pretty sure this is due to a recent change in core. The utterance may now be none (when stt times out), and that's not handled right now. Will push the fix next time I'm in front of a computer
