### ISSUE TITLE
start command conflicts with Spotify skill

### ISSUE THREAD

**Issue by clebio** [forslund/white-house-adventure#6]
When I say `play Zork`, mycroft responds 
> An error occurred while processing a request in Spotify skill

which isn't surprising, but yeah, that sucks.

**Comment by clebio** [comment]
Here's what I see in the log: 
```
11:58:11.051 - SKILLS - DEBUG - {"data": {"utterance": "play zork", "lang": "en-US"}, "context": {"client_name": "mycroft_listener", "ident": "1528718289.859662-745090242"}, "type": "intent_failure"}
11:58:11.061 - mycroft.skills.padatious_service:handle_fallback:110 - DEBUG - Padatious fallback attempt: play zork
11:58:11.079 - SKILLS - DEBUG - {"data": {"handler": "fallback"}, "context": {"client_name": "mycroft_listener", "ident": "1528718289.859662-745090242"}, "type": "mycroft.skill.handler.start"}
11:58:11.106 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
11:58:11.116 - SKILLS - DEBUG - {"data": {"utterance": "play zork", "track": "zork"}, "context": {"client_name": "mycroft_listener", "ident": "1528718289.859662-745090242"}, "type": "mycroft-spotify.forslund:PlaySong.intent"}
11:58:11.142 - SKILLS - DEBUG - {"data": {"fallback_handler": "PadatiousService.handle_fallback", "handler": "fallback"}, "context": {"client_name": "mycroft_listener", "ident": "1528718289.859662-745090242"}, "type": "mycroft.skill.handler.complete"}
11:58:11.144 - mycroft-spotify_forslund:play_song:526 - DEBUG - I'm in the play_song handler but I've seen an utterance that contains 'playlist.' I want to play the playlist play. Switching handlers.
11:58:11.150 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.spotify.com
11:58:11.180 - SKILLS - DEBUG - {"data": {"name": "SpotifySkill.play_song"}, "context": {"client_name": "mycroft_listener", "ident": "1528718289.859662-745090242"}, "type": "mycroft.skill.handler.start"}
11:58:11.326 - requests.packages.urllib3.connectionpool - DEBUG - https://api.spotify.com:443 "GET /v1/me/player/devices HTTP/1.1" 200 None
11:58:11.343 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.spotify.com
11:58:11.347 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/device/48dcf2cd-df8e-4ace-acd1-d91a7c54cac8/metric/timing HTTP/1.1" 200 278
11:58:11.370 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/device/48dcf2cd-df8e-4ace-acd1-d91a7c54cac8/metric/timing HTTP/1.1" 200 294
11:58:11.522 - requests.packages.urllib3.connectionpool - DEBUG - https://api.spotify.com:443 "GET /v1/me/player/devices HTTP/1.1" 200 None
11:58:11.543 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.spotify.com
11:58:11.708 - requests.packages.urllib3.connectionpool - DEBUG - https://api.spotify.com:443 "GET /v1/me/player/devices HTTP/1.1" 200 None
11:58:11.725 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.spotify.com
11:58:11.910 - requests.packages.urllib3.connectionpool - DEBUG - https://api.spotify.com:443 "GET /v1/me/player/devices HTTP/1.1" 200 None
11:58:11.934 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.spotify.com
11:58:12.119 - requests.packages.urllib3.connectionpool - DEBUG - https://api.spotify.com:443 "GET /v1/me/playlists?offset=0&limit=50 HTTP/1.1" 200 None
11:58:12.145 - mycroft.skills.core:wrapper:607 - ERROR - An error occurred while processing a request in Spotify Skill
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/skills/core.py", line 598, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 528, in play_song
    self.play_playlist(message)
  File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 600, in play_playlist
    self.start_playlist_playback(dev, self.get_best_playlist(playlist))
  File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 485, in get_best_playlist
    key, confidence = match_one(playlist, self.playlists.keys())
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/util/parse.py", line 56, in match_one
    raise ValueError('a list or dict of choices must be provided')
ValueError: a list or dict of choices must be provided
11:58:12.151 - SKILLS - DEBUG - {"data": {"utterance": "An error occurred while processing a request in Spotify Skill", "expect_response": false}, "context": {"client_name": "mycroft_listener", "ident": "1528718289.859662-745090242"}, "type": "speak"}
11:58:12.165 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai```

**Comment by forslund** [comment]
Hi, the playback of the spotify skill is now using the common play framework so this should be resolved. Closing now, if this is still an issue feel free to reopen.
